version: '3.4'
services:
  nginx:
    image: nginx:1.18.0
    ports:
      - "${LISTEN_NGINX_HTTP}:80"
    restart: unless-stopped
    volumes:
      - "./nginx/${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf:ro"
      - "./index.html:/usr/share/nginx/html/index.html:ro"
      - "./index.js:/usr/share/nginx/html/index.js:ro"
      - "./art.js:/usr/share/nginx/html/art.js:ro"
      - "./art:/usr/share/nginx/html/art:ro"
